version: '3'

services:
  app:
    build: .
    volumes:
#      - ${PWD}/build/libs/test.war:/usr/local/tomcat/webapps/ROOT.war
      - ${PWD}/build/libs:/usr/local/tomcat/webapps
    ports:
    - "8080:8080"
