global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
# - job_name: 'node'
#   static_configs:
#   - targets: ['node-exporter:9100']

# - job_name: 'postgres'
#   static_configs:
#   - targets: ['postgres-exporter:9187']

- job_name: 'statsd'
  static_configs:
  - targets: ['statsd-exporter:9102']