version: '3'

services:
#  app:
#    build: ./app
#    volumes:
#      - ${PWD}/app/build/libs:/usr/local/tomcat/webapps
#    ports:
#      - "8080:8080"
#      - "8000:8000"
#    environment:
#      JPDA_ADDRESS: 8000
#      JPDA_TRANSPORT: dt_socket
#      DATABASE_URL: jdbc:postgresql://postgres:54321/testdb
#      DATABASE_USER: user
#      DATABASE_PASSWORD: pass
#    depends_on:
#      - postgres

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
