version: '3'

services:
#  app:
#    build: ./app
#    volumes:
#      - ${PWD}/app/build/libs:/usr/local/tomcat/webapps
#    ports:
#      - "8080:8080"
#      - "8000:8000"
#    environment:
#      JPDA_ADDRESS: 8000
#      JPDA_TRANSPORT: dt_socket
#      DATABASE_URL: jdbc:postgresql://postgres:54321/cdcdb
#      DATABASE_USER: user
#      DATABASE_PASSWORD: pass
#    depends_on:
#      - postgres

  db:
    build: ./db
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cdcdb

  pg_amqp_bridge:
    image: subzerocloud/pg-amqp-bridge
    depends_on:
      - db
      - rabbitmq
    environment:
      - POSTGRESQL_URI=postgres://user:pass@db:5432/cdcdb
      - AMQP_URI=amqp://user:pass@rabbitmq//
      - BRIDGE_CHANNELS=events:events

    # RabbitMQ instance can be used to consolidate events that originated in your database/application.
    # You can connect here with different consumers and take actions based on those events (like sending signup emails)
  rabbitmq:
    build: ./rabbit
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
#    environment:
#      - RABBITMQ_DEFAULT_USER=user
#      - RABBITMQ_DEFAULT_PASS=pass