apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: postgres
data:
  POSTGRES_DB: cG9zdGdyZXNkYg== #postgresdb
  POSTGRES_USER: cG9zdGdyZXNhZG1pbg== #postgresadmin
  POSTGRES_PASSWORD: YWRtaW4xMjM= #admin123
