FROM tomcat:alpine

#RUN ["rm", "-fr", "/usr/local/tomcat/webapps/ROOT"]

#ADD ./build/libs/test.war /usr/local/tomcat/webapps/ROOT.war

#COPY ./build/libs/test.war /usr/local/tomcat/webapps/ROOT.war

#CMD ["catalina.sh", "run"]