version: '3'

services:
<<<<<<< Updated upstream
  app:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/testdb

  postgres:
    image: postgres:9.6.2-alpine
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
=======
  api:
    environment:
      - NODE_ENV=development
    user: root
    build:
      context: ./api
      args:
        - NODE_ENV=development
    ports:
      - 3000:3000
    # command: nodemon src/index.js
    volumes:
      - ./api/:/usr/src/app

    # command: ls -la /usr/src/app/src
    command: ls -la
>>>>>>> Stashed changes
