version: '3'

services:
#  producer:
#    build: ./producer
#    volumes:
#      - ${PWD}/out/artifacts/app:/usr/app
#    ports:
#      - "8080:8080"
#    environment:
#      JPDA_ADDRESS: 8000
#      JPDA_TRANSPORT: dt_socket
#      AMQP_HOST: rabbitmq
#      AMQP_USER: user
#      AMQP_PASS: pass
#    depends_on:
#      - rabbitmq
#    restart: on-failure:10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
