apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-postgres
  name: k8s-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: k8s-postgres
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-postgres-lb
  name: k8s-postgres-lb
spec:
  type: LoadBalancer
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: k8s-postgres