apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8s-postgres
spec:
  selector:
    matchLabels:
      app: k8s-postgres # has to match .spec.template.metadata.labels
  serviceName: k8s-postgres
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: k8s-postgres # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:9.6.2-alpine
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: k8s-db-volume
  volumeClaimTemplates:
  - metadata:
      name: k8s-db-volume
      labels:
        app: k8s-postgres
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi